// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/handwriting.proto

package handwriting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to generate a new handwriting practice sheet
type GenerateSheetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SheetId       string                 `protobuf:"bytes,1,opt,name=sheet_id,json=sheetId,proto3" json:"sheet_id,omitempty"` // Unique identifier for the sheet
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                      // Text to practice writing
	Style         string                 `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`                    // Style: "lines", "dotted", "blank"
	Repetitions   int32                  `protobuf:"varint,4,opt,name=repetitions,proto3" json:"repetitions,omitempty"`       // Number of times to repeat the text (default: 5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSheetRequest) Reset() {
	*x = GenerateSheetRequest{}
	mi := &file_proto_handwriting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSheetRequest) ProtoMessage() {}

func (x *GenerateSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handwriting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSheetRequest.ProtoReflect.Descriptor instead.
func (*GenerateSheetRequest) Descriptor() ([]byte, []int) {
	return file_proto_handwriting_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateSheetRequest) GetSheetId() string {
	if x != nil {
		return x.SheetId
	}
	return ""
}

func (x *GenerateSheetRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateSheetRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *GenerateSheetRequest) GetRepetitions() int32 {
	if x != nil {
		return x.Repetitions
	}
	return 0
}

// Response after generating a sheet
type GenerateSheetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SheetId       string                 `protobuf:"bytes,1,opt,name=sheet_id,json=sheetId,proto3" json:"sheet_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Style         string                 `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	Repetitions   int32                  `protobuf:"varint,4,opt,name=repetitions,proto3" json:"repetitions,omitempty"`
	SvgContent    string                 `protobuf:"bytes,5,opt,name=svg_content,json=svgContent,proto3" json:"svg_content,omitempty"` // SVG content of the sheet
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`   // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSheetResponse) Reset() {
	*x = GenerateSheetResponse{}
	mi := &file_proto_handwriting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSheetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSheetResponse) ProtoMessage() {}

func (x *GenerateSheetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handwriting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSheetResponse.ProtoReflect.Descriptor instead.
func (*GenerateSheetResponse) Descriptor() ([]byte, []int) {
	return file_proto_handwriting_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateSheetResponse) GetSheetId() string {
	if x != nil {
		return x.SheetId
	}
	return ""
}

func (x *GenerateSheetResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateSheetResponse) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *GenerateSheetResponse) GetRepetitions() int32 {
	if x != nil {
		return x.Repetitions
	}
	return 0
}

func (x *GenerateSheetResponse) GetSvgContent() string {
	if x != nil {
		return x.SvgContent
	}
	return ""
}

func (x *GenerateSheetResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Request to get an existing sheet
type GetSheetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SheetId       string                 `protobuf:"bytes,1,opt,name=sheet_id,json=sheetId,proto3" json:"sheet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSheetRequest) Reset() {
	*x = GetSheetRequest{}
	mi := &file_proto_handwriting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSheetRequest) ProtoMessage() {}

func (x *GetSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handwriting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSheetRequest.ProtoReflect.Descriptor instead.
func (*GetSheetRequest) Descriptor() ([]byte, []int) {
	return file_proto_handwriting_proto_rawDescGZIP(), []int{2}
}

func (x *GetSheetRequest) GetSheetId() string {
	if x != nil {
		return x.SheetId
	}
	return ""
}

// Response with sheet details
type GetSheetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SheetId       string                 `protobuf:"bytes,1,opt,name=sheet_id,json=sheetId,proto3" json:"sheet_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Style         string                 `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	Repetitions   int32                  `protobuf:"varint,4,opt,name=repetitions,proto3" json:"repetitions,omitempty"`
	SvgContent    string                 `protobuf:"bytes,5,opt,name=svg_content,json=svgContent,proto3" json:"svg_content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Exists        bool                   `protobuf:"varint,7,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSheetResponse) Reset() {
	*x = GetSheetResponse{}
	mi := &file_proto_handwriting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSheetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSheetResponse) ProtoMessage() {}

func (x *GetSheetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handwriting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSheetResponse.ProtoReflect.Descriptor instead.
func (*GetSheetResponse) Descriptor() ([]byte, []int) {
	return file_proto_handwriting_proto_rawDescGZIP(), []int{3}
}

func (x *GetSheetResponse) GetSheetId() string {
	if x != nil {
		return x.SheetId
	}
	return ""
}

func (x *GetSheetResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GetSheetResponse) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *GetSheetResponse) GetRepetitions() int32 {
	if x != nil {
		return x.Repetitions
	}
	return 0
}

func (x *GetSheetResponse) GetSvgContent() string {
	if x != nil {
		return x.SvgContent
	}
	return ""
}

func (x *GetSheetResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetSheetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// Request to list all sheets for a service
type ListSheetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSheetsRequest) Reset() {
	*x = ListSheetsRequest{}
	mi := &file_proto_handwriting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSheetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSheetsRequest) ProtoMessage() {}

func (x *ListSheetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handwriting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSheetsRequest.ProtoReflect.Descriptor instead.
func (*ListSheetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_handwriting_proto_rawDescGZIP(), []int{4}
}

// Response with list of sheet IDs
type ListSheetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SheetIds      []string               `protobuf:"bytes,1,rep,name=sheet_ids,json=sheetIds,proto3" json:"sheet_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSheetsResponse) Reset() {
	*x = ListSheetsResponse{}
	mi := &file_proto_handwriting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSheetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSheetsResponse) ProtoMessage() {}

func (x *ListSheetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handwriting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSheetsResponse.ProtoReflect.Descriptor instead.
func (*ListSheetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_handwriting_proto_rawDescGZIP(), []int{5}
}

func (x *ListSheetsResponse) GetSheetIds() []string {
	if x != nil {
		return x.SheetIds
	}
	return nil
}

// Request to delete a sheet
type DeleteSheetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SheetId       string                 `protobuf:"bytes,1,opt,name=sheet_id,json=sheetId,proto3" json:"sheet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSheetRequest) Reset() {
	*x = DeleteSheetRequest{}
	mi := &file_proto_handwriting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSheetRequest) ProtoMessage() {}

func (x *DeleteSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handwriting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSheetRequest.ProtoReflect.Descriptor instead.
func (*DeleteSheetRequest) Descriptor() ([]byte, []int) {
	return file_proto_handwriting_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSheetRequest) GetSheetId() string {
	if x != nil {
		return x.SheetId
	}
	return ""
}

// Response after deleting a sheet
type DeleteSheetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSheetResponse) Reset() {
	*x = DeleteSheetResponse{}
	mi := &file_proto_handwriting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSheetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSheetResponse) ProtoMessage() {}

func (x *DeleteSheetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handwriting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSheetResponse.ProtoReflect.Descriptor instead.
func (*DeleteSheetResponse) Descriptor() ([]byte, []int) {
	return file_proto_handwriting_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSheetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_handwriting_proto protoreflect.FileDescriptor

const file_proto_handwriting_proto_rawDesc = "" +
	"\n" +
	"\x17proto/handwriting.proto\x12\vhandwriting\"}\n" +
	"\x14GenerateSheetRequest\x12\x19\n" +
	"\bsheet_id\x18\x01 \x01(\tR\asheetId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05style\x18\x03 \x01(\tR\x05style\x12 \n" +
	"\vrepetitions\x18\x04 \x01(\x05R\vrepetitions\"\xbe\x01\n" +
	"\x15GenerateSheetResponse\x12\x19\n" +
	"\bsheet_id\x18\x01 \x01(\tR\asheetId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05style\x18\x03 \x01(\tR\x05style\x12 \n" +
	"\vrepetitions\x18\x04 \x01(\x05R\vrepetitions\x12\x1f\n" +
	"\vsvg_content\x18\x05 \x01(\tR\n" +
	"svgContent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\",\n" +
	"\x0fGetSheetRequest\x12\x19\n" +
	"\bsheet_id\x18\x01 \x01(\tR\asheetId\"\xd1\x01\n" +
	"\x10GetSheetResponse\x12\x19\n" +
	"\bsheet_id\x18\x01 \x01(\tR\asheetId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05style\x18\x03 \x01(\tR\x05style\x12 \n" +
	"\vrepetitions\x18\x04 \x01(\x05R\vrepetitions\x12\x1f\n" +
	"\vsvg_content\x18\x05 \x01(\tR\n" +
	"svgContent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06exists\x18\a \x01(\bR\x06exists\"\x13\n" +
	"\x11ListSheetsRequest\"1\n" +
	"\x12ListSheetsResponse\x12\x1b\n" +
	"\tsheet_ids\x18\x01 \x03(\tR\bsheetIds\"/\n" +
	"\x12DeleteSheetRequest\x12\x19\n" +
	"\bsheet_id\x18\x01 \x01(\tR\asheetId\"/\n" +
	"\x13DeleteSheetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessBDZBgithub.com/xiaonanln/goverse/samples/handwriting/proto;handwritingb\x06proto3"

var (
	file_proto_handwriting_proto_rawDescOnce sync.Once
	file_proto_handwriting_proto_rawDescData []byte
)

func file_proto_handwriting_proto_rawDescGZIP() []byte {
	file_proto_handwriting_proto_rawDescOnce.Do(func() {
		file_proto_handwriting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_handwriting_proto_rawDesc), len(file_proto_handwriting_proto_rawDesc)))
	})
	return file_proto_handwriting_proto_rawDescData
}

var file_proto_handwriting_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_handwriting_proto_goTypes = []any{
	(*GenerateSheetRequest)(nil),  // 0: handwriting.GenerateSheetRequest
	(*GenerateSheetResponse)(nil), // 1: handwriting.GenerateSheetResponse
	(*GetSheetRequest)(nil),       // 2: handwriting.GetSheetRequest
	(*GetSheetResponse)(nil),      // 3: handwriting.GetSheetResponse
	(*ListSheetsRequest)(nil),     // 4: handwriting.ListSheetsRequest
	(*ListSheetsResponse)(nil),    // 5: handwriting.ListSheetsResponse
	(*DeleteSheetRequest)(nil),    // 6: handwriting.DeleteSheetRequest
	(*DeleteSheetResponse)(nil),   // 7: handwriting.DeleteSheetResponse
}
var file_proto_handwriting_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_handwriting_proto_init() }
func file_proto_handwriting_proto_init() {
	if File_proto_handwriting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_handwriting_proto_rawDesc), len(file_proto_handwriting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_handwriting_proto_goTypes,
		DependencyIndexes: file_proto_handwriting_proto_depIdxs,
		MessageInfos:      file_proto_handwriting_proto_msgTypes,
	}.Build()
	File_proto_handwriting_proto = out.File
	file_proto_handwriting_proto_goTypes = nil
	file_proto_handwriting_proto_depIdxs = nil
}
