codecov:
  require_ci_to_pass: no
  # Wait for all 3 coverage uploads (test.yml, chat.yml, chat-clustered.yml) 
  # before reporting project status to avoid false failures when tests haven't finished
  after_n_builds: 3
  precision: 2
  round: down
  layout: "reach,diff,flags,tree"
  show_contextual_diff: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        informational: true
        target: 70
        threshold: 5
        branches: main,develop
    patch:
      default:
        informational: true
        target: 0

ignore:
  - "**/*_pb2.py"
  - "**/*_grpc.pb.go"
  - "**/*_pb2_grpc.py"
  - "**/proto"
  - "tests/"
  - "samples/chat/client"
  - "default.etcd/"
  - "docker/"
  - "script/"

flags:
  go:
    carryforward: yes
  integration:
    carryforward: yes

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: yes
  require_head: yes
  show_carryforward_flags: yes

branches:
  - main
  - develop
