codecov:
  require_ci_to_pass: no
  # Wait for all 10 coverage uploads before reporting project status to avoid false failures when tests haven't finished
  # test.yml: coverage.out, coverage-etcd-restart.out, coverage-parallel.out
  # samples.yml: coverage-chat.out, coverage-chat-clustered.out, coverage-counter.out, coverage-counter-clustered.out, coverage-tictactoe.out, coverage-tictactoe-clustered.out
  # concurrency.yml: coverage-concurrency.out
  after_n_builds: 10
  precision: 2
  round: down
  layout: "reach,diff,flags,tree"
  show_contextual_diff: yes

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        informational: true
        target: 50
        threshold: 5
        branches: main,develop
    patch:
      default:
        informational: true
        target: 0

ignore:
  - "**/*_pb2.py"
  - "**/*_grpc.pb.go"
  - "**/*_pb2_grpc.py"
  - "**/proto"
  - "tests/"
  - "samples/chat/client"
  - "default.etcd/"
  - "docker/"
  - "script/"

flags:
  go:
    carryforward: yes
  integration:
    carryforward: yes

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: yes
  require_head: yes
  show_carryforward_flags: yes

branches:
  - main
  - develop
