package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

const (
	defaultShards = 8192
)

func main() {
	var (
		numNodes      = flag.Int("nodes", 1, "Number of nodes to generate")
		numGates      = flag.Int("gates", 1, "Number of gates to generate")
		withInspector = flag.Bool("inspector", true, "Include inspector configuration")
	)

	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: %s [options] <filename.yml>\n\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "Generate a GoVerse configuration file with the specified topology.\n\n")
		fmt.Fprintf(os.Stderr, "Options:\n")
		flag.PrintDefaults()
		fmt.Fprintf(os.Stderr, "\nExample:\n")
		fmt.Fprintf(os.Stderr, "  %s --nodes 3 --gates 2 --inspector=true config.yml\n", os.Args[0])
	}

	flag.Parse()

	if flag.NArg() != 1 {
		fmt.Fprintf(os.Stderr, "Error: output filename required\n\n")
		flag.Usage()
		os.Exit(1)
	}

	filename := flag.Arg(0)

	if *numNodes < 1 {
		fmt.Fprintf(os.Stderr, "Error: number of nodes must be at least 1\n")
		os.Exit(1)
	}

	if *numGates < 0 {
		fmt.Fprintf(os.Stderr, "Error: number of gates cannot be negative\n")
		os.Exit(1)
	}

	if err := generateConfig(filename, *numNodes, *numGates, *withInspector); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Configuration file generated: %s\n\n", filename)
	printUsageInstructions(filename, *numNodes, *numGates, *withInspector)
}

func generateConfig(filename string, numNodes, numGates int, withInspector bool) error {
	file, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer file.Close()

	var sb strings.Builder

	// Header
	sb.WriteString("# GoVerse Configuration File\n")
	sb.WriteString("# Generated by: go run ./cmd/configgen\n")
	sb.WriteString("#\n")
	sb.WriteString("# This configuration defines the cluster topology, nodes, gates, and coordination settings.\n")
	sb.WriteString("# See docs/CONFIGURATION.md for complete documentation.\n")
	sb.WriteString("\n")

	// Version
	sb.WriteString("# Configuration schema version (required)\n")
	sb.WriteString("version: 1\n")
	sb.WriteString("\n")

	// Cluster configuration
	sb.WriteString("# Cluster coordination settings\n")
	sb.WriteString("cluster:\n")
	sb.WriteString(fmt.Sprintf("  # Number of shards for object distribution (default: %d)\n", defaultShards))
	sb.WriteString(fmt.Sprintf("  shards: %d\n", defaultShards))
	sb.WriteString("\n")
	sb.WriteString("  # Cluster coordination provider - currently only 'etcd' is supported\n")
	sb.WriteString("  provider: \"etcd\"\n")
	sb.WriteString("\n")
	sb.WriteString("  # etcd configuration\n")
	sb.WriteString("  etcd:\n")
	sb.WriteString("    # List of etcd endpoints (default: [\"localhost:2379\"])\n")
	sb.WriteString("    endpoints:\n")
	sb.WriteString("      - \"localhost:2379\"\n")
	sb.WriteString("    \n")
	sb.WriteString("    # Key prefix for GoVerse data in etcd (default: \"/goverse\")\n")
	sb.WriteString("    prefix: \"/goverse\"\n")
	sb.WriteString("\n")

	// PostgreSQL configuration
	sb.WriteString("# PostgreSQL persistence configuration (optional)\n")
	sb.WriteString("# Uncomment and configure to enable persistence\n")
	sb.WriteString("# postgres:\n")
	sb.WriteString("#   # Database host (default: \"localhost\")\n")
	sb.WriteString("#   host: \"localhost\"\n")
	sb.WriteString("#   \n")
	sb.WriteString("#   # Database port (default: 5432)\n")
	sb.WriteString("#   port: 5432\n")
	sb.WriteString("#   \n")
	sb.WriteString("#   # Database user (default: \"postgres\")\n")
	sb.WriteString("#   user: \"postgres\"\n")
	sb.WriteString("#   \n")
	sb.WriteString("#   # Database password (default: \"\")\n")
	sb.WriteString("#   # It's recommended to use environment variables for passwords\n")
	sb.WriteString("#   password: \"\"\n")
	sb.WriteString("#   \n")
	sb.WriteString("#   # Database name (default: \"goverse\")\n")
	sb.WriteString("#   database: \"goverse\"\n")
	sb.WriteString("#   \n")
	sb.WriteString("#   # SSL mode - use \"require\" for production (default: \"disable\")\n")
	sb.WriteString("#   sslmode: \"disable\"\n")
	sb.WriteString("\n")

	// Inspector configuration
	if withInspector {
		sb.WriteString("# Inspector service configuration for monitoring and debugging (optional)\n")
		sb.WriteString("# The inspector provides a web UI for visualizing the cluster topology\n")
		sb.WriteString("inspector:\n")
		sb.WriteString("  # gRPC server address for inspector API (default: \"127.0.0.1:9081\")\n")
		sb.WriteString("  grpc_addr: \"127.0.0.1:9081\"\n")
		sb.WriteString("  \n")
		sb.WriteString("  # HTTP server address for inspector web UI (default: \"127.0.0.1:8080\")\n")
		sb.WriteString("  http_addr: \"127.0.0.1:8080\"\n")
		sb.WriteString("  \n")
		sb.WriteString("  # Address that nodes and gates use to connect to inspector (default: \"localhost:9081\")\n")
		sb.WriteString("  advertise_addr: \"localhost:9081\"\n")
		sb.WriteString("\n")
	} else {
		sb.WriteString("# Inspector service configuration (optional)\n")
		sb.WriteString("# Uncomment to enable the inspector service for monitoring and debugging\n")
		sb.WriteString("# inspector:\n")
		sb.WriteString("#   # gRPC server address for inspector API (default: \"127.0.0.1:9081\")\n")
		sb.WriteString("#   grpc_addr: \"127.0.0.1:9081\"\n")
		sb.WriteString("#   \n")
		sb.WriteString("#   # HTTP server address for inspector web UI (default: \"127.0.0.1:8080\")\n")
		sb.WriteString("#   http_addr: \"127.0.0.1:8080\"\n")
		sb.WriteString("#   \n")
		sb.WriteString("#   # Address that nodes and gates use to connect to inspector (default: \"localhost:9081\")\n")
		sb.WriteString("#   advertise_addr: \"localhost:9081\"\n")
		sb.WriteString("\n")
	}

	// Nodes configuration
	sb.WriteString("# Node configurations\n")
	sb.WriteString("# Nodes host distributed objects and handle object lifecycle\n")
	sb.WriteString("nodes:\n")
	for i := 1; i <= numNodes; i++ {
		nodeID := fmt.Sprintf("node-%d", i)
		grpcPort := 50050 + i
		// Start node HTTP ports at 8081 to avoid conflict with inspector on 8080
		httpPort := 8080 + i

		if i > 1 {
			sb.WriteString("\n")
		}
		sb.WriteString(fmt.Sprintf("  - # Node %d\n", i))
		sb.WriteString(fmt.Sprintf("    id: \"%s\"\n", nodeID))
		sb.WriteString("    \n")
		sb.WriteString(fmt.Sprintf("    # gRPC listen address (default: \"127.0.0.1:%d\")\n", grpcPort))
		sb.WriteString(fmt.Sprintf("    grpc_addr: \"127.0.0.1:%d\"\n", grpcPort))
		sb.WriteString("    \n")
		sb.WriteString(fmt.Sprintf("    # Address other nodes use to reach this node (default: \"localhost:%d\")\n", grpcPort))
		sb.WriteString(fmt.Sprintf("    advertise_addr: \"localhost:%d\"\n", grpcPort))
		sb.WriteString("    \n")
		sb.WriteString(fmt.Sprintf("    # HTTP address for metrics and admin endpoints (default: \"127.0.0.1:%d\")\n", httpPort))
		sb.WriteString(fmt.Sprintf("    http_addr: \"127.0.0.1:%d\"\n", httpPort))
	}
	sb.WriteString("\n")

	// Gates configuration
	sb.WriteString("# Gate configurations\n")
	sb.WriteString("# Gates are entry points for client connections (gRPC and HTTP)\n")
	if numGates == 0 {
		sb.WriteString("# No gates configured - uncomment and add entries as needed\n")
		sb.WriteString("gates: []\n")
		sb.WriteString("# gates:\n")
		sb.WriteString("#   - id: \"gate-1\"\n")
		sb.WriteString("#     \n")
		sb.WriteString("#     # gRPC listen address for client connections (default: \"127.0.0.1:60051\")\n")
		sb.WriteString("#     grpc_addr: \"127.0.0.1:60051\"\n")
		sb.WriteString("#     \n")
		sb.WriteString("#     # Advertised address for the gate (optional, defaults to grpc_addr)\n")
		sb.WriteString("#     advertise_addr: \"localhost:60051\"\n")
		sb.WriteString("#     \n")
		sb.WriteString("#     # HTTP address for REST API and metrics (optional)\n")
		sb.WriteString("#     http_addr: \"127.0.0.1:8090\"\n")
	} else {
		sb.WriteString("gates:\n")
		for i := 1; i <= numGates; i++ {
			gateID := fmt.Sprintf("gate-%d", i)
			grpcPort := 60050 + i
			httpPort := 8089 + i

			if i > 1 {
				sb.WriteString("\n")
			}
			sb.WriteString(fmt.Sprintf("  - # Gate %d\n", i))
			sb.WriteString(fmt.Sprintf("    id: \"%s\"\n", gateID))
			sb.WriteString("    \n")
			sb.WriteString(fmt.Sprintf("    # gRPC listen address for client connections (default: \"127.0.0.1:%d\")\n", grpcPort))
			sb.WriteString(fmt.Sprintf("    grpc_addr: \"127.0.0.1:%d\"\n", grpcPort))
			sb.WriteString("    \n")
			sb.WriteString(fmt.Sprintf("    # Advertised address for the gate (optional, defaults to grpc_addr)\n"))
			sb.WriteString(fmt.Sprintf("    advertise_addr: \"localhost:%d\"\n", grpcPort))
			sb.WriteString("    \n")
			sb.WriteString(fmt.Sprintf("    # HTTP address for REST API and metrics (optional)\n"))
			sb.WriteString(fmt.Sprintf("    http_addr: \"127.0.0.1:%d\"\n", httpPort))
		}
	}
	sb.WriteString("\n")

	// Access control rules
	sb.WriteString("# Object access control rules (optional)\n")
	sb.WriteString("# Controls which clients and nodes can call methods on objects\n")
	sb.WriteString("# Uncomment to enable access control\n")
	sb.WriteString("# object_access_rules:\n")
	sb.WriteString("#   # Allow all access (development mode)\n")
	sb.WriteString("#   - type: /.*/\n")
	sb.WriteString("#     access: ALLOW\n")
	sb.WriteString("\n")

	// Lifecycle rules
	sb.WriteString("# Object lifecycle control rules (optional)\n")
	sb.WriteString("# Controls which clients and nodes can create or delete objects\n")
	sb.WriteString("# Uncomment to enable lifecycle control\n")
	sb.WriteString("# object_lifecycle_rules:\n")
	sb.WriteString("#   # Example: restrict deletion to internal nodes only\n")
	sb.WriteString("#   - type: /.*/\n")
	sb.WriteString("#     lifecycle: DELETE\n")
	sb.WriteString("#     access: INTERNAL\n")

	if _, err := file.WriteString(sb.String()); err != nil {
		return fmt.Errorf("failed to write to file: %w", err)
	}

	return nil
}

func printUsageInstructions(filename string, numNodes, numGates int, withInspector bool) {
	fmt.Println("Configuration file generated successfully!")
	fmt.Println()
	fmt.Println("Usage Instructions:")
	fmt.Println("==================")
	fmt.Println()

	// Prerequisites
	fmt.Println("1. Prerequisites:")
	fmt.Println("   - Ensure etcd is running on localhost:2379")
	fmt.Println("   - Or update the etcd endpoints in the config file")
	fmt.Println()

	stepNum := 2

	// Starting inspector
	if withInspector {
		fmt.Printf("%d. Start the Inspector (optional, for monitoring):\n", stepNum)
		fmt.Println("   go run ./cmd/inspector/")
		fmt.Println()
		stepNum++
	}

	// Starting nodes
	if numNodes == 1 {
		fmt.Printf("%d. Start the Node:\n", stepNum)
		fmt.Printf("   go run <your-app> --config %s --node-id node-1\n", filename)
		fmt.Println()
	} else {
		fmt.Printf("%d. Start the Nodes (in separate terminals):\n", stepNum)
		for i := 1; i <= numNodes; i++ {
			fmt.Printf("   Terminal %d: go run <your-app> --config %s --node-id node-%d\n", i, filename, i)
		}
		fmt.Println()
	}
	stepNum++

	// Starting gates
	if numGates > 0 {
		if numGates == 1 {
			fmt.Printf("%d. Start the Gate:\n", stepNum)
			fmt.Printf("   go run ./cmd/gate/ --config %s --gate-id gate-1\n", filename)
			fmt.Println()
		} else {
			fmt.Printf("%d. Start the Gates (in separate terminals):\n", stepNum)
			for i := 1; i <= numGates; i++ {
				fmt.Printf("   Terminal %d: go run ./cmd/gate/ --config %s --gate-id gate-%d\n", i, filename, i)
			}
			fmt.Println()
		}
	}

	// Accessing services
	fmt.Println("Accessing Services:")
	fmt.Println("-------------------")
	if withInspector {
		fmt.Println("- Inspector Web UI: http://127.0.0.1:8080")
	}
	if numNodes > 0 {
		for i := 1; i <= numNodes; i++ {
			// Node HTTP ports start at 8081 to avoid conflict with inspector on 8080
			httpPort := 8080 + i
			fmt.Printf("- Node %d metrics: http://127.0.0.1:%d/metrics\n", i, httpPort)
		}
	}
	if numGates > 0 {
		for i := 1; i <= numGates; i++ {
			httpPort := 8089 + i
			fmt.Printf("- Gate %d HTTP API: http://127.0.0.1:%d\n", i, httpPort)
		}
	}
	fmt.Println()

	// Additional notes
	fmt.Println("Notes:")
	fmt.Println("------")
	fmt.Println("- Replace <your-app> with your GoVerse application path")
	fmt.Println("- See docs/CONFIGURATION.md for detailed configuration options")
	fmt.Println("- Modify addresses and ports in the config file as needed")
	fmt.Println("- Use environment variables for sensitive data like PostgreSQL passwords")
	fmt.Println()
}
