// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: samples/chat/proto/chat.proto

package chat_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in microseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Client_ListChatRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_ListChatRoomsRequest) Reset() {
	*x = Client_ListChatRoomsRequest{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_ListChatRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_ListChatRoomsRequest) ProtoMessage() {}

func (x *Client_ListChatRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_ListChatRoomsRequest.ProtoReflect.Descriptor instead.
func (*Client_ListChatRoomsRequest) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{1}
}

// Response containing a list of available chat rooms
type Client_ListChatRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRooms     []string               `protobuf:"bytes,1,rep,name=chat_rooms,json=chatRooms,proto3" json:"chat_rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_ListChatRoomsResponse) Reset() {
	*x = Client_ListChatRoomsResponse{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_ListChatRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_ListChatRoomsResponse) ProtoMessage() {}

func (x *Client_ListChatRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_ListChatRoomsResponse.ProtoReflect.Descriptor instead.
func (*Client_ListChatRoomsResponse) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{2}
}

func (x *Client_ListChatRoomsResponse) GetChatRooms() []string {
	if x != nil {
		return x.ChatRooms
	}
	return nil
}

type ChatRoom_ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoom_ListRequest) Reset() {
	*x = ChatRoom_ListRequest{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoom_ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoom_ListRequest) ProtoMessage() {}

func (x *ChatRoom_ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoom_ListRequest.ProtoReflect.Descriptor instead.
func (*ChatRoom_ListRequest) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{3}
}

// Represents a chat message
type ChatRoom_ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRooms     []string               `protobuf:"bytes,1,rep,name=chat_rooms,json=chatRooms,proto3" json:"chat_rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoom_ListResponse) Reset() {
	*x = ChatRoom_ListResponse{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoom_ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoom_ListResponse) ProtoMessage() {}

func (x *ChatRoom_ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoom_ListResponse.ProtoReflect.Descriptor instead.
func (*ChatRoom_ListResponse) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ChatRoom_ListResponse) GetChatRooms() []string {
	if x != nil {
		return x.ChatRooms
	}
	return nil
}

type Client_JoinChatRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_JoinChatRoomRequest) Reset() {
	*x = Client_JoinChatRoomRequest{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_JoinChatRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_JoinChatRoomRequest) ProtoMessage() {}

func (x *Client_JoinChatRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_JoinChatRoomRequest.ProtoReflect.Descriptor instead.
func (*Client_JoinChatRoomRequest) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{5}
}

func (x *Client_JoinChatRoomRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *Client_JoinChatRoomRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type Client_JoinChatRoomResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomName       string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	RecentMessages []*ChatMessage         `protobuf:"bytes,2,rep,name=recent_messages,json=recentMessages,proto3" json:"recent_messages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Client_JoinChatRoomResponse) Reset() {
	*x = Client_JoinChatRoomResponse{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_JoinChatRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_JoinChatRoomResponse) ProtoMessage() {}

func (x *Client_JoinChatRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_JoinChatRoomResponse.ProtoReflect.Descriptor instead.
func (*Client_JoinChatRoomResponse) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{6}
}

func (x *Client_JoinChatRoomResponse) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *Client_JoinChatRoomResponse) GetRecentMessages() []*ChatMessage {
	if x != nil {
		return x.RecentMessages
	}
	return nil
}

type Client_SendChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_SendChatMessageRequest) Reset() {
	*x = Client_SendChatMessageRequest{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_SendChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_SendChatMessageRequest) ProtoMessage() {}

func (x *Client_SendChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_SendChatMessageRequest.ProtoReflect.Descriptor instead.
func (*Client_SendChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{7}
}

func (x *Client_SendChatMessageRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *Client_SendChatMessageRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Client_SendChatMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Client_SendChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_SendChatMessageResponse) Reset() {
	*x = Client_SendChatMessageResponse{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_SendChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_SendChatMessageResponse) ProtoMessage() {}

func (x *Client_SendChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_SendChatMessageResponse.ProtoReflect.Descriptor instead.
func (*Client_SendChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{8}
}

type Client_GetRecentMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomName       string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	AfterTimestamp int64                  `protobuf:"varint,2,opt,name=after_timestamp,json=afterTimestamp,proto3" json:"after_timestamp,omitempty"` // Unix timestamp in microseconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Client_GetRecentMessagesRequest) Reset() {
	*x = Client_GetRecentMessagesRequest{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_GetRecentMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_GetRecentMessagesRequest) ProtoMessage() {}

func (x *Client_GetRecentMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_GetRecentMessagesRequest.ProtoReflect.Descriptor instead.
func (*Client_GetRecentMessagesRequest) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{9}
}

func (x *Client_GetRecentMessagesRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *Client_GetRecentMessagesRequest) GetAfterTimestamp() int64 {
	if x != nil {
		return x.AfterTimestamp
	}
	return 0
}

type Client_GetRecentMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_GetRecentMessagesResponse) Reset() {
	*x = Client_GetRecentMessagesResponse{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_GetRecentMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_GetRecentMessagesResponse) ProtoMessage() {}

func (x *Client_GetRecentMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_GetRecentMessagesResponse.ProtoReflect.Descriptor instead.
func (*Client_GetRecentMessagesResponse) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{10}
}

func (x *Client_GetRecentMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ChatRoom_JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Client ID for push notifications
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoom_JoinRequest) Reset() {
	*x = ChatRoom_JoinRequest{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoom_JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoom_JoinRequest) ProtoMessage() {}

func (x *ChatRoom_JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoom_JoinRequest.ProtoReflect.Descriptor instead.
func (*ChatRoom_JoinRequest) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ChatRoom_JoinRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ChatRoom_JoinRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ChatRoom_JoinResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomName       string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	RecentMessages []*ChatMessage         `protobuf:"bytes,2,rep,name=recent_messages,json=recentMessages,proto3" json:"recent_messages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRoom_JoinResponse) Reset() {
	*x = ChatRoom_JoinResponse{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoom_JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoom_JoinResponse) ProtoMessage() {}

func (x *ChatRoom_JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoom_JoinResponse.ProtoReflect.Descriptor instead.
func (*ChatRoom_JoinResponse) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{12}
}

func (x *ChatRoom_JoinResponse) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *ChatRoom_JoinResponse) GetRecentMessages() []*ChatMessage {
	if x != nil {
		return x.RecentMessages
	}
	return nil
}

type ChatRoom_SendChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoom_SendChatMessageRequest) Reset() {
	*x = ChatRoom_SendChatMessageRequest{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoom_SendChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoom_SendChatMessageRequest) ProtoMessage() {}

func (x *ChatRoom_SendChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoom_SendChatMessageRequest.ProtoReflect.Descriptor instead.
func (*ChatRoom_SendChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{13}
}

func (x *ChatRoom_SendChatMessageRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ChatRoom_SendChatMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChatRoom_SendChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoom_SendChatMessageResponse) Reset() {
	*x = ChatRoom_SendChatMessageResponse{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoom_SendChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoom_SendChatMessageResponse) ProtoMessage() {}

func (x *ChatRoom_SendChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoom_SendChatMessageResponse.ProtoReflect.Descriptor instead.
func (*ChatRoom_SendChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{14}
}

type ChatRoom_GetRecentMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AfterTimestamp int64                  `protobuf:"varint,1,opt,name=after_timestamp,json=afterTimestamp,proto3" json:"after_timestamp,omitempty"` // Unix timestamp in microseconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRoom_GetRecentMessagesRequest) Reset() {
	*x = ChatRoom_GetRecentMessagesRequest{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoom_GetRecentMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoom_GetRecentMessagesRequest) ProtoMessage() {}

func (x *ChatRoom_GetRecentMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoom_GetRecentMessagesRequest.ProtoReflect.Descriptor instead.
func (*ChatRoom_GetRecentMessagesRequest) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{15}
}

func (x *ChatRoom_GetRecentMessagesRequest) GetAfterTimestamp() int64 {
	if x != nil {
		return x.AfterTimestamp
	}
	return 0
}

type ChatRoom_GetRecentMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoom_GetRecentMessagesResponse) Reset() {
	*x = ChatRoom_GetRecentMessagesResponse{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoom_GetRecentMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoom_GetRecentMessagesResponse) ProtoMessage() {}

func (x *ChatRoom_GetRecentMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoom_GetRecentMessagesResponse.ProtoReflect.Descriptor instead.
func (*ChatRoom_GetRecentMessagesResponse) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{16}
}

func (x *ChatRoom_GetRecentMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Message pushed to clients when a new chat message arrives
type Client_NewMessageNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_NewMessageNotification) Reset() {
	*x = Client_NewMessageNotification{}
	mi := &file_samples_chat_proto_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_NewMessageNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_NewMessageNotification) ProtoMessage() {}

func (x *Client_NewMessageNotification) ProtoReflect() protoreflect.Message {
	mi := &file_samples_chat_proto_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_NewMessageNotification.ProtoReflect.Descriptor instead.
func (*Client_NewMessageNotification) Descriptor() ([]byte, []int) {
	return file_samples_chat_proto_chat_proto_rawDescGZIP(), []int{17}
}

func (x *Client_NewMessageNotification) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_samples_chat_proto_chat_proto protoreflect.FileDescriptor

const file_samples_chat_proto_chat_proto_rawDesc = "" +
	"\n" +
	"\x1dsamples/chat/proto/chat.proto\x12\x04chat\"b\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x1d\n" +
	"\x1bClient_ListChatRoomsRequest\"=\n" +
	"\x1cClient_ListChatRoomsResponse\x12\x1d\n" +
	"\n" +
	"chat_rooms\x18\x01 \x03(\tR\tchatRooms\"\x16\n" +
	"\x14ChatRoom_ListRequest\"6\n" +
	"\x15ChatRoom_ListResponse\x12\x1d\n" +
	"\n" +
	"chat_rooms\x18\x01 \x03(\tR\tchatRooms\"V\n" +
	"\x1aClient_JoinChatRoomRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"v\n" +
	"\x1bClient_JoinChatRoomResponse\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12:\n" +
	"\x0frecent_messages\x18\x02 \x03(\v2\x11.chat.ChatMessageR\x0erecentMessages\"s\n" +
	"\x1dClient_SendChatMessageRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\" \n" +
	"\x1eClient_SendChatMessageResponse\"g\n" +
	"\x1fClient_GetRecentMessagesRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12'\n" +
	"\x0fafter_timestamp\x18\x02 \x01(\x03R\x0eafterTimestamp\"Q\n" +
	" Client_GetRecentMessagesResponse\x12-\n" +
	"\bmessages\x18\x01 \x03(\v2\x11.chat.ChatMessageR\bmessages\"P\n" +
	"\x14ChatRoom_JoinRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"p\n" +
	"\x15ChatRoom_JoinResponse\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12:\n" +
	"\x0frecent_messages\x18\x02 \x03(\v2\x11.chat.ChatMessageR\x0erecentMessages\"X\n" +
	"\x1fChatRoom_SendChatMessageRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\"\n" +
	" ChatRoom_SendChatMessageResponse\"L\n" +
	"!ChatRoom_GetRecentMessagesRequest\x12'\n" +
	"\x0fafter_timestamp\x18\x01 \x01(\x03R\x0eafterTimestamp\"S\n" +
	"\"ChatRoom_GetRecentMessagesResponse\x12-\n" +
	"\bmessages\x18\x01 \x03(\v2\x11.chat.ChatMessageR\bmessages\"L\n" +
	"\x1dClient_NewMessageNotification\x12+\n" +
	"\amessage\x18\x01 \x01(\v2\x11.chat.ChatMessageR\amessageB3Z1github.com/xiaonanln/goverse/samples/chat/chat_pbb\x06proto3"

var (
	file_samples_chat_proto_chat_proto_rawDescOnce sync.Once
	file_samples_chat_proto_chat_proto_rawDescData []byte
)

func file_samples_chat_proto_chat_proto_rawDescGZIP() []byte {
	file_samples_chat_proto_chat_proto_rawDescOnce.Do(func() {
		file_samples_chat_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_samples_chat_proto_chat_proto_rawDesc), len(file_samples_chat_proto_chat_proto_rawDesc)))
	})
	return file_samples_chat_proto_chat_proto_rawDescData
}

var file_samples_chat_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_samples_chat_proto_chat_proto_goTypes = []any{
	(*ChatMessage)(nil),                        // 0: chat.ChatMessage
	(*Client_ListChatRoomsRequest)(nil),        // 1: chat.Client_ListChatRoomsRequest
	(*Client_ListChatRoomsResponse)(nil),       // 2: chat.Client_ListChatRoomsResponse
	(*ChatRoom_ListRequest)(nil),               // 3: chat.ChatRoom_ListRequest
	(*ChatRoom_ListResponse)(nil),              // 4: chat.ChatRoom_ListResponse
	(*Client_JoinChatRoomRequest)(nil),         // 5: chat.Client_JoinChatRoomRequest
	(*Client_JoinChatRoomResponse)(nil),        // 6: chat.Client_JoinChatRoomResponse
	(*Client_SendChatMessageRequest)(nil),      // 7: chat.Client_SendChatMessageRequest
	(*Client_SendChatMessageResponse)(nil),     // 8: chat.Client_SendChatMessageResponse
	(*Client_GetRecentMessagesRequest)(nil),    // 9: chat.Client_GetRecentMessagesRequest
	(*Client_GetRecentMessagesResponse)(nil),   // 10: chat.Client_GetRecentMessagesResponse
	(*ChatRoom_JoinRequest)(nil),               // 11: chat.ChatRoom_JoinRequest
	(*ChatRoom_JoinResponse)(nil),              // 12: chat.ChatRoom_JoinResponse
	(*ChatRoom_SendChatMessageRequest)(nil),    // 13: chat.ChatRoom_SendChatMessageRequest
	(*ChatRoom_SendChatMessageResponse)(nil),   // 14: chat.ChatRoom_SendChatMessageResponse
	(*ChatRoom_GetRecentMessagesRequest)(nil),  // 15: chat.ChatRoom_GetRecentMessagesRequest
	(*ChatRoom_GetRecentMessagesResponse)(nil), // 16: chat.ChatRoom_GetRecentMessagesResponse
	(*Client_NewMessageNotification)(nil),      // 17: chat.Client_NewMessageNotification
}
var file_samples_chat_proto_chat_proto_depIdxs = []int32{
	0, // 0: chat.Client_JoinChatRoomResponse.recent_messages:type_name -> chat.ChatMessage
	0, // 1: chat.Client_GetRecentMessagesResponse.messages:type_name -> chat.ChatMessage
	0, // 2: chat.ChatRoom_JoinResponse.recent_messages:type_name -> chat.ChatMessage
	0, // 3: chat.ChatRoom_GetRecentMessagesResponse.messages:type_name -> chat.ChatMessage
	0, // 4: chat.Client_NewMessageNotification.message:type_name -> chat.ChatMessage
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_samples_chat_proto_chat_proto_init() }
func file_samples_chat_proto_chat_proto_init() {
	if File_samples_chat_proto_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_samples_chat_proto_chat_proto_rawDesc), len(file_samples_chat_proto_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_samples_chat_proto_chat_proto_goTypes,
		DependencyIndexes: file_samples_chat_proto_chat_proto_depIdxs,
		MessageInfos:      file_samples_chat_proto_chat_proto_msgTypes,
	}.Build()
	File_samples_chat_proto_chat_proto = out.File
	file_samples_chat_proto_chat_proto_goTypes = nil
	file_samples_chat_proto_chat_proto_depIdxs = nil
}
