# Use official Golang image as the base
FROM golang:1.25-bookworm

# Install protoc (protobuf compiler) and git
RUN apt-get update && apt-get install -y dos2unix protobuf-compiler git && rm -rf /var/lib/apt/lists/*

# Install protoc-gen-go and protoc-gen-go-grpc
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

# Make sure /go/bin is on PATH
ENV PATH="/go/bin:${PATH}"

# Set working directory
WORKDIR /app

# Copy the entire project to /app
COPY . .

# Download Go dependencies
RUN go mod download

# Default command
CMD ["bash"]
