// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/goverse.proto

package goverse_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Goverse_Status_FullMethodName              = "/goverse.Goverse/Status"
	Goverse_ListObjects_FullMethodName         = "/goverse.Goverse/ListObjects"
	Goverse_CallObject_FullMethodName          = "/goverse.Goverse/CallObject"
	Goverse_CreateObject_FullMethodName        = "/goverse.Goverse/CreateObject"
	Goverse_PushMessageToClient_FullMethodName = "/goverse.Goverse/PushMessageToClient"
)

// GoverseClient is the client API for Goverse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoverseClient interface {
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	ListObjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListObjectsResponse, error)
	CallObject(ctx context.Context, in *CallObjectRequest, opts ...grpc.CallOption) (*CallObjectResponse, error)
	CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*CreateObjectResponse, error)
	PushMessageToClient(ctx context.Context, in *PushMessageToClientRequest, opts ...grpc.CallOption) (*PushMessageToClientResponse, error)
}

type goverseClient struct {
	cc grpc.ClientConnInterface
}

func NewGoverseClient(cc grpc.ClientConnInterface) GoverseClient {
	return &goverseClient{cc}
}

func (c *goverseClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Goverse_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goverseClient) ListObjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, Goverse_ListObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goverseClient) CallObject(ctx context.Context, in *CallObjectRequest, opts ...grpc.CallOption) (*CallObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallObjectResponse)
	err := c.cc.Invoke(ctx, Goverse_CallObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goverseClient) CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*CreateObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateObjectResponse)
	err := c.cc.Invoke(ctx, Goverse_CreateObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goverseClient) PushMessageToClient(ctx context.Context, in *PushMessageToClientRequest, opts ...grpc.CallOption) (*PushMessageToClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushMessageToClientResponse)
	err := c.cc.Invoke(ctx, Goverse_PushMessageToClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoverseServer is the server API for Goverse service.
// All implementations must embed UnimplementedGoverseServer
// for forward compatibility.
type GoverseServer interface {
	Status(context.Context, *Empty) (*StatusResponse, error)
	ListObjects(context.Context, *Empty) (*ListObjectsResponse, error)
	CallObject(context.Context, *CallObjectRequest) (*CallObjectResponse, error)
	CreateObject(context.Context, *CreateObjectRequest) (*CreateObjectResponse, error)
	PushMessageToClient(context.Context, *PushMessageToClientRequest) (*PushMessageToClientResponse, error)
	mustEmbedUnimplementedGoverseServer()
}

// UnimplementedGoverseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoverseServer struct{}

func (UnimplementedGoverseServer) Status(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedGoverseServer) ListObjects(context.Context, *Empty) (*ListObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedGoverseServer) CallObject(context.Context, *CallObjectRequest) (*CallObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallObject not implemented")
}
func (UnimplementedGoverseServer) CreateObject(context.Context, *CreateObjectRequest) (*CreateObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateObject not implemented")
}
func (UnimplementedGoverseServer) PushMessageToClient(context.Context, *PushMessageToClientRequest) (*PushMessageToClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMessageToClient not implemented")
}
func (UnimplementedGoverseServer) mustEmbedUnimplementedGoverseServer() {}
func (UnimplementedGoverseServer) testEmbeddedByValue()                 {}

// UnsafeGoverseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoverseServer will
// result in compilation errors.
type UnsafeGoverseServer interface {
	mustEmbedUnimplementedGoverseServer()
}

func RegisterGoverseServer(s grpc.ServiceRegistrar, srv GoverseServer) {
	// If the following call pancis, it indicates UnimplementedGoverseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Goverse_ServiceDesc, srv)
}

func _Goverse_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoverseServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goverse_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoverseServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goverse_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoverseServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goverse_ListObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoverseServer).ListObjects(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goverse_CallObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoverseServer).CallObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goverse_CallObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoverseServer).CallObject(ctx, req.(*CallObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goverse_CreateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoverseServer).CreateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goverse_CreateObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoverseServer).CreateObject(ctx, req.(*CreateObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goverse_PushMessageToClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMessageToClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoverseServer).PushMessageToClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goverse_PushMessageToClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoverseServer).PushMessageToClient(ctx, req.(*PushMessageToClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Goverse_ServiceDesc is the grpc.ServiceDesc for Goverse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Goverse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goverse.Goverse",
	HandlerType: (*GoverseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Goverse_Status_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _Goverse_ListObjects_Handler,
		},
		{
			MethodName: "CallObject",
			Handler:    _Goverse_CallObject_Handler,
		},
		{
			MethodName: "CreateObject",
			Handler:    _Goverse_CreateObject_Handler,
		},
		{
			MethodName: "PushMessageToClient",
			Handler:    _Goverse_PushMessageToClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/goverse.proto",
}
