// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/goverse.proto

package goverse_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdvertiseAddr string                 `protobuf:"bytes,1,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	NumObjects    int64                  `protobuf:"varint,2,opt,name=num_objects,json=numObjects,proto3" json:"num_objects,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_goverse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goverse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_goverse_proto_rawDescGZIP(), []int{0}
}

func (x *StatusResponse) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *StatusResponse) GetNumObjects() int64 {
	if x != nil {
		return x.NumObjects
	}
	return 0
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type CallObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Request       *anypb.Any             `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallObjectRequest) Reset() {
	*x = CallObjectRequest{}
	mi := &file_proto_goverse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallObjectRequest) ProtoMessage() {}

func (x *CallObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goverse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallObjectRequest.ProtoReflect.Descriptor instead.
func (*CallObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_goverse_proto_rawDescGZIP(), []int{1}
}

func (x *CallObjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CallObjectRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallObjectRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CallObjectRequest) GetRequest() *anypb.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

type CallObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *anypb.Any             `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallObjectResponse) Reset() {
	*x = CallObjectResponse{}
	mi := &file_proto_goverse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallObjectResponse) ProtoMessage() {}

func (x *CallObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goverse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallObjectResponse.ProtoReflect.Descriptor instead.
func (*CallObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_goverse_proto_rawDescGZIP(), []int{2}
}

func (x *CallObjectResponse) GetResponse() *anypb.Any {
	if x != nil {
		return x.Response
	}
	return nil
}

type CreateObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	InitData      *anypb.Any             `protobuf:"bytes,2,opt,name=init_data,json=initData,proto3" json:"init_data,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"` // Optional: if not provided, the node will generate an ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObjectRequest) Reset() {
	*x = CreateObjectRequest{}
	mi := &file_proto_goverse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjectRequest) ProtoMessage() {}

func (x *CreateObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goverse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjectRequest.ProtoReflect.Descriptor instead.
func (*CreateObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_goverse_proto_rawDescGZIP(), []int{3}
}

func (x *CreateObjectRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateObjectRequest) GetInitData() *anypb.Any {
	if x != nil {
		return x.InitData
	}
	return nil
}

func (x *CreateObjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObjectResponse) Reset() {
	*x = CreateObjectResponse{}
	mi := &file_proto_goverse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjectResponse) ProtoMessage() {}

func (x *CreateObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goverse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjectResponse.ProtoReflect.Descriptor instead.
func (*CreateObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_goverse_proto_rawDescGZIP(), []int{4}
}

func (x *CreateObjectResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ObjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	CreationTime  int64                  `protobuf:"varint,3,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"` // Unix timestamp in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectInfo) Reset() {
	*x = ObjectInfo{}
	mi := &file_proto_goverse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectInfo) ProtoMessage() {}

func (x *ObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goverse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectInfo.ProtoReflect.Descriptor instead.
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return file_proto_goverse_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ObjectInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectInfo) GetCreationTime() int64 {
	if x != nil {
		return x.CreationTime
	}
	return 0
}

type ListObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*ObjectInfo          `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_proto_goverse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goverse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_goverse_proto_rawDescGZIP(), []int{6}
}

func (x *ListObjectsResponse) GetObjects() []*ObjectInfo {
	if x != nil {
		return x.Objects
	}
	return nil
}

type PushMessageToClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Message       *anypb.Any             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessageToClientRequest) Reset() {
	*x = PushMessageToClientRequest{}
	mi := &file_proto_goverse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageToClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageToClientRequest) ProtoMessage() {}

func (x *PushMessageToClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goverse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageToClientRequest.ProtoReflect.Descriptor instead.
func (*PushMessageToClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_goverse_proto_rawDescGZIP(), []int{7}
}

func (x *PushMessageToClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PushMessageToClientRequest) GetMessage() *anypb.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

type PushMessageToClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessageToClientResponse) Reset() {
	*x = PushMessageToClientResponse{}
	mi := &file_proto_goverse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageToClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageToClientResponse) ProtoMessage() {}

func (x *PushMessageToClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goverse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageToClientResponse.ProtoReflect.Descriptor instead.
func (*PushMessageToClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_goverse_proto_rawDescGZIP(), []int{8}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_goverse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goverse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_goverse_proto_rawDescGZIP(), []int{9}
}

var File_proto_goverse_proto protoreflect.FileDescriptor

const file_proto_goverse_proto_rawDesc = "" +
	"\n" +
	"\x13proto/goverse.proto\x12\agoverse\x1a\x19google/protobuf/any.proto\"\x7f\n" +
	"\x0eStatusResponse\x12%\n" +
	"\x0eadvertise_addr\x18\x01 \x01(\tR\radvertiseAddr\x12\x1f\n" +
	"\vnum_objects\x18\x02 \x01(\x03R\n" +
	"numObjects\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"\x7f\n" +
	"\x11CallObjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12.\n" +
	"\arequest\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\arequest\"F\n" +
	"\x12CallObjectResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\bresponse\"l\n" +
	"\x13CreateObjectRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x121\n" +
	"\tinit_data\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\binitData\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"&\n" +
	"\x14CreateObjectResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\n" +
	"ObjectInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12#\n" +
	"\rcreation_time\x18\x03 \x01(\x03R\fcreationTime\"D\n" +
	"\x13ListObjectsResponse\x12-\n" +
	"\aobjects\x18\x01 \x03(\v2\x13.goverse.ObjectInfoR\aobjects\"i\n" +
	"\x1aPushMessageToClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12.\n" +
	"\amessage\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\amessage\"\x1d\n" +
	"\x1bPushMessageToClientResponse\"\a\n" +
	"\x05Empty2\xef\x02\n" +
	"\aGoverse\x121\n" +
	"\x06Status\x12\x0e.goverse.Empty\x1a\x17.goverse.StatusResponse\x12;\n" +
	"\vListObjects\x12\x0e.goverse.Empty\x1a\x1c.goverse.ListObjectsResponse\x12E\n" +
	"\n" +
	"CallObject\x12\x1a.goverse.CallObjectRequest\x1a\x1b.goverse.CallObjectResponse\x12K\n" +
	"\fCreateObject\x12\x1c.goverse.CreateObjectRequest\x1a\x1d.goverse.CreateObjectResponse\x12`\n" +
	"\x13PushMessageToClient\x12#.goverse.PushMessageToClientRequest\x1a$.goverse.PushMessageToClientResponseB/Z-github.com/xiaonanln/goverse/proto/goverse_pbb\x06proto3"

var (
	file_proto_goverse_proto_rawDescOnce sync.Once
	file_proto_goverse_proto_rawDescData []byte
)

func file_proto_goverse_proto_rawDescGZIP() []byte {
	file_proto_goverse_proto_rawDescOnce.Do(func() {
		file_proto_goverse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_goverse_proto_rawDesc), len(file_proto_goverse_proto_rawDesc)))
	})
	return file_proto_goverse_proto_rawDescData
}

var file_proto_goverse_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_goverse_proto_goTypes = []any{
	(*StatusResponse)(nil),              // 0: goverse.StatusResponse
	(*CallObjectRequest)(nil),           // 1: goverse.CallObjectRequest
	(*CallObjectResponse)(nil),          // 2: goverse.CallObjectResponse
	(*CreateObjectRequest)(nil),         // 3: goverse.CreateObjectRequest
	(*CreateObjectResponse)(nil),        // 4: goverse.CreateObjectResponse
	(*ObjectInfo)(nil),                  // 5: goverse.ObjectInfo
	(*ListObjectsResponse)(nil),         // 6: goverse.ListObjectsResponse
	(*PushMessageToClientRequest)(nil),  // 7: goverse.PushMessageToClientRequest
	(*PushMessageToClientResponse)(nil), // 8: goverse.PushMessageToClientResponse
	(*Empty)(nil),                       // 9: goverse.Empty
	(*anypb.Any)(nil),                   // 10: google.protobuf.Any
}
var file_proto_goverse_proto_depIdxs = []int32{
	10, // 0: goverse.CallObjectRequest.request:type_name -> google.protobuf.Any
	10, // 1: goverse.CallObjectResponse.response:type_name -> google.protobuf.Any
	10, // 2: goverse.CreateObjectRequest.init_data:type_name -> google.protobuf.Any
	5,  // 3: goverse.ListObjectsResponse.objects:type_name -> goverse.ObjectInfo
	10, // 4: goverse.PushMessageToClientRequest.message:type_name -> google.protobuf.Any
	9,  // 5: goverse.Goverse.Status:input_type -> goverse.Empty
	9,  // 6: goverse.Goverse.ListObjects:input_type -> goverse.Empty
	1,  // 7: goverse.Goverse.CallObject:input_type -> goverse.CallObjectRequest
	3,  // 8: goverse.Goverse.CreateObject:input_type -> goverse.CreateObjectRequest
	7,  // 9: goverse.Goverse.PushMessageToClient:input_type -> goverse.PushMessageToClientRequest
	0,  // 10: goverse.Goverse.Status:output_type -> goverse.StatusResponse
	6,  // 11: goverse.Goverse.ListObjects:output_type -> goverse.ListObjectsResponse
	2,  // 12: goverse.Goverse.CallObject:output_type -> goverse.CallObjectResponse
	4,  // 13: goverse.Goverse.CreateObject:output_type -> goverse.CreateObjectResponse
	8,  // 14: goverse.Goverse.PushMessageToClient:output_type -> goverse.PushMessageToClientResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_goverse_proto_init() }
func file_proto_goverse_proto_init() {
	if File_proto_goverse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_goverse_proto_rawDesc), len(file_proto_goverse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_goverse_proto_goTypes,
		DependencyIndexes: file_proto_goverse_proto_depIdxs,
		MessageInfos:      file_proto_goverse_proto_msgTypes,
	}.Build()
	File_proto_goverse_proto = out.File
	file_proto_goverse_proto_goTypes = nil
	file_proto_goverse_proto_depIdxs = nil
}
