// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: inspector/proto/inspector.proto

package inspector_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_inspector_proto_inspector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_inspector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_inspector_proto_inspector_proto_rawDescGZIP(), []int{0}
}

type Object struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_inspector_proto_inspector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_inspector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_inspector_proto_inspector_proto_rawDescGZIP(), []int{1}
}

func (x *Object) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Object) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddOrUpdateObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *Object                `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	NodeAddress   string                 `protobuf:"bytes,2,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"` // e.g. "localhost:47000"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdateObjectRequest) Reset() {
	*x = AddOrUpdateObjectRequest{}
	mi := &file_inspector_proto_inspector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdateObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdateObjectRequest) ProtoMessage() {}

func (x *AddOrUpdateObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_inspector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdateObjectRequest.ProtoReflect.Descriptor instead.
func (*AddOrUpdateObjectRequest) Descriptor() ([]byte, []int) {
	return file_inspector_proto_inspector_proto_rawDescGZIP(), []int{2}
}

func (x *AddOrUpdateObjectRequest) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *AddOrUpdateObjectRequest) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

type RegisterNodeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AdvertiseAddress string                 `protobuf:"bytes,1,opt,name=advertise_address,json=advertiseAddress,proto3" json:"advertise_address,omitempty"` // e.g. "localhost:47000"
	Objects          []*Object              `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_inspector_proto_inspector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_inspector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_inspector_proto_inspector_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterNodeRequest) GetAdvertiseAddress() string {
	if x != nil {
		return x.AdvertiseAddress
	}
	return ""
}

func (x *RegisterNodeRequest) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_inspector_proto_inspector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_inspector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_inspector_proto_inspector_proto_rawDescGZIP(), []int{4}
}

type UnregisterNodeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AdvertiseAddress string                 `protobuf:"bytes,1,opt,name=advertise_address,json=advertiseAddress,proto3" json:"advertise_address,omitempty"` // e.g. "localhost:47000"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UnregisterNodeRequest) Reset() {
	*x = UnregisterNodeRequest{}
	mi := &file_inspector_proto_inspector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterNodeRequest) ProtoMessage() {}

func (x *UnregisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inspector_proto_inspector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterNodeRequest.ProtoReflect.Descriptor instead.
func (*UnregisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_inspector_proto_inspector_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterNodeRequest) GetAdvertiseAddress() string {
	if x != nil {
		return x.AdvertiseAddress
	}
	return ""
}

var File_inspector_proto_inspector_proto protoreflect.FileDescriptor

const file_inspector_proto_inspector_proto_rawDesc = "" +
	"\n" +
	"\x1finspector/proto/inspector.proto\x12\tinspector\"\a\n" +
	"\x05Empty\".\n" +
	"\x06Object\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"h\n" +
	"\x18AddOrUpdateObjectRequest\x12)\n" +
	"\x06object\x18\x01 \x01(\v2\x11.inspector.ObjectR\x06object\x12!\n" +
	"\fnode_address\x18\x02 \x01(\tR\vnodeAddress\"o\n" +
	"\x13RegisterNodeRequest\x12+\n" +
	"\x11advertise_address\x18\x01 \x01(\tR\x10advertiseAddress\x12+\n" +
	"\aobjects\x18\x02 \x03(\v2\x11.inspector.ObjectR\aobjects\"\x16\n" +
	"\x14RegisterNodeResponse\"D\n" +
	"\x15UnregisterNodeRequest\x12+\n" +
	"\x11advertise_address\x18\x01 \x01(\tR\x10advertiseAddress2\xa1\x02\n" +
	"\x10InspectorService\x12J\n" +
	"\x11AddOrUpdateObject\x12#.inspector.AddOrUpdateObjectRequest\x1a\x10.inspector.Empty\x12O\n" +
	"\fRegisterNode\x12\x1e.inspector.RegisterNodeRequest\x1a\x1f.inspector.RegisterNodeResponse\x12D\n" +
	"\x0eUnregisterNode\x12 .inspector.UnregisterNodeRequest\x1a\x10.inspector.Empty\x12*\n" +
	"\x04Ping\x12\x10.inspector.Empty\x1a\x10.inspector.EmptyB;Z9github.com/xiaonanln/goverse/inspector/proto/inspector_pbb\x06proto3"

var (
	file_inspector_proto_inspector_proto_rawDescOnce sync.Once
	file_inspector_proto_inspector_proto_rawDescData []byte
)

func file_inspector_proto_inspector_proto_rawDescGZIP() []byte {
	file_inspector_proto_inspector_proto_rawDescOnce.Do(func() {
		file_inspector_proto_inspector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inspector_proto_inspector_proto_rawDesc), len(file_inspector_proto_inspector_proto_rawDesc)))
	})
	return file_inspector_proto_inspector_proto_rawDescData
}

var file_inspector_proto_inspector_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_inspector_proto_inspector_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: inspector.Empty
	(*Object)(nil),                   // 1: inspector.Object
	(*AddOrUpdateObjectRequest)(nil), // 2: inspector.AddOrUpdateObjectRequest
	(*RegisterNodeRequest)(nil),      // 3: inspector.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),     // 4: inspector.RegisterNodeResponse
	(*UnregisterNodeRequest)(nil),    // 5: inspector.UnregisterNodeRequest
}
var file_inspector_proto_inspector_proto_depIdxs = []int32{
	1, // 0: inspector.AddOrUpdateObjectRequest.object:type_name -> inspector.Object
	1, // 1: inspector.RegisterNodeRequest.objects:type_name -> inspector.Object
	2, // 2: inspector.InspectorService.AddOrUpdateObject:input_type -> inspector.AddOrUpdateObjectRequest
	3, // 3: inspector.InspectorService.RegisterNode:input_type -> inspector.RegisterNodeRequest
	5, // 4: inspector.InspectorService.UnregisterNode:input_type -> inspector.UnregisterNodeRequest
	0, // 5: inspector.InspectorService.Ping:input_type -> inspector.Empty
	0, // 6: inspector.InspectorService.AddOrUpdateObject:output_type -> inspector.Empty
	4, // 7: inspector.InspectorService.RegisterNode:output_type -> inspector.RegisterNodeResponse
	0, // 8: inspector.InspectorService.UnregisterNode:output_type -> inspector.Empty
	0, // 9: inspector.InspectorService.Ping:output_type -> inspector.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inspector_proto_inspector_proto_init() }
func file_inspector_proto_inspector_proto_init() {
	if File_inspector_proto_inspector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inspector_proto_inspector_proto_rawDesc), len(file_inspector_proto_inspector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inspector_proto_inspector_proto_goTypes,
		DependencyIndexes: file_inspector_proto_inspector_proto_depIdxs,
		MessageInfos:      file_inspector_proto_inspector_proto_msgTypes,
	}.Build()
	File_inspector_proto_inspector_proto = out.File
	file_inspector_proto_inspector_proto_goTypes = nil
	file_inspector_proto_inspector_proto_depIdxs = nil
}
