// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: client/proto/client.proto

package client_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterResponse is the first message that the client can receive from the Register stream
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_client_proto_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_client_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Request       *anypb.Any             `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_client_proto_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_client_proto_rawDescGZIP(), []int{1}
}

func (x *CallRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest) GetRequest() *anypb.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *anypb.Any             `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_client_proto_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_client_proto_rawDescGZIP(), []int{2}
}

func (x *CallResponse) GetResponse() *anypb.Any {
	if x != nil {
		return x.Response
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_client_proto_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_client_proto_client_proto_rawDescGZIP(), []int{3}
}

var File_client_proto_client_proto protoreflect.FileDescriptor

const file_client_proto_client_proto_rawDesc = "" +
	"\n" +
	"\x19client/proto/client.proto\x12\x06client\x1a\x19google/protobuf/any.proto\"/\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"r\n" +
	"\vCallRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12.\n" +
	"\arequest\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\arequest\"@\n" +
	"\fCallResponse\x120\n" +
	"\bresponse\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\bresponse\"\a\n" +
	"\x05Empty2u\n" +
	"\rClientService\x121\n" +
	"\bRegister\x12\r.client.Empty\x1a\x14.google.protobuf.Any0\x01\x121\n" +
	"\x04Call\x12\x13.client.CallRequest\x1a\x14.client.CallResponseB5Z3github.com/xiaonanln/goverse/client/proto/client_pbb\x06proto3"

var (
	file_client_proto_client_proto_rawDescOnce sync.Once
	file_client_proto_client_proto_rawDescData []byte
)

func file_client_proto_client_proto_rawDescGZIP() []byte {
	file_client_proto_client_proto_rawDescOnce.Do(func() {
		file_client_proto_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_client_proto_rawDesc), len(file_client_proto_client_proto_rawDesc)))
	})
	return file_client_proto_client_proto_rawDescData
}

var file_client_proto_client_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_client_proto_client_proto_goTypes = []any{
	(*RegisterResponse)(nil), // 0: client.RegisterResponse
	(*CallRequest)(nil),      // 1: client.CallRequest
	(*CallResponse)(nil),     // 2: client.CallResponse
	(*Empty)(nil),            // 3: client.Empty
	(*anypb.Any)(nil),        // 4: google.protobuf.Any
}
var file_client_proto_client_proto_depIdxs = []int32{
	4, // 0: client.CallRequest.request:type_name -> google.protobuf.Any
	4, // 1: client.CallResponse.response:type_name -> google.protobuf.Any
	3, // 2: client.ClientService.Register:input_type -> client.Empty
	1, // 3: client.ClientService.Call:input_type -> client.CallRequest
	4, // 4: client.ClientService.Register:output_type -> google.protobuf.Any
	2, // 5: client.ClientService.Call:output_type -> client.CallResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_client_proto_client_proto_init() }
func file_client_proto_client_proto_init() {
	if File_client_proto_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_client_proto_rawDesc), len(file_client_proto_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_proto_client_proto_goTypes,
		DependencyIndexes: file_client_proto_client_proto_depIdxs,
		MessageInfos:      file_client_proto_client_proto_msgTypes,
	}.Build()
	File_client_proto_client_proto = out.File
	file_client_proto_client_proto_goTypes = nil
	file_client_proto_client_proto_depIdxs = nil
}
